name = "link-shortener-worker"
type = "javascript"
account_id = "your-cloudflare-account-id"
workers_dev = true
compatibility_date = "2024-08-04"

kv_namespaces = [
    { binding = "LINKS", id = "your-kv-id", preview_id = "your-preview-kv-id" }
]
